charlist/charlist/urls.py
from django.contrib import admin
from django.urls import path, include
from charlist.settings import DEBUG

import personages.views as personages
import myauth.views as myauth

urlpatterns = [
    path('personage/', include('personages.urls', namespace='personages')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('all_personages/', personages.all_personages, name='all_personages'),

    path('admin/', admin.site.urls),
]

# if DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls'))

charlist/myauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
import myauth.views as myauth

app_name = 'myauth'

urlpatterns = [

    path('register/', myauth.NewUserRegister.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

charlist/personages/urls.py
from django.contrib import admin
from django.urls import path, include
from charlist.settings import DEBUG

import personages.views as personages

app_name = 'personages'

urlpatterns = [

    path('details/<int:pk>/', personages.PersonageDetailView.as_view(), name='details'),
    path('create/', personages.PersonageCreateView.as_view(), name='create'),
    path('update/<int:pk>/', personages.PersonageUpdateView.as_view(), name='update'),

]

charlist/myauth/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models


# расширение дефолтного User
# class NewUserProfile(models.Model):
#     user = models.OneToOneField(User,
#                                 on_delete=models.CASCADE,
#                                 primary_key=True)
#     avatar = models.ImageField(upload_to='avatars', blank=True)

class CharlistUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True)

charlist/personages/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from myauth.models import CharlistUser


class Personage(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id = models.ForeignKey(CharlistUser, on_delete=models.SET_NULL, null=True)
    # group_id = models.ForeignKey(на группу пользователей)
    pers_name = models.CharField(max_length=64)
    pers_pronoun = models.CharField(max_length=64)
    pers_description = models.TextField(blank=True)
    refresh = models.IntegerField(null=True)
    fate_points = models.IntegerField(null=True)
    aspect1 = models.CharField(max_length=256, blank=True)
    aspect2 = models.CharField(max_length=256, blank=True)
    aspect3 = models.CharField(max_length=256, blank=True)
    aspect4 = models.CharField(max_length=256, blank=True)
    aspect5 = models.CharField(max_length=256, blank=True)
    approach1_name = models.CharField(max_length=256, blank=True)
    approach1_value = models.IntegerField(null=True)
    approach2_name = models.CharField(max_length=256, blank=True)
    approach2_value = models.IntegerField(null=True)
    approach3_name = models.CharField(max_length=256, blank=True)
    approach3_value = models.IntegerField(null=True)
    approach4_name = models.CharField(max_length=256, blank=True)
    approach4_value = models.IntegerField(null=True)
    approach5_name = models.CharField(max_length=256, blank=True)
    approach5_value = models.IntegerField(null=True)
    approach6_name = models.CharField(max_length=256, blank=True)
    approach6_value = models.IntegerField(null=True)
    stunts = models.TextField(blank=True)
    extras = models.TextField(blank=True)
    stress = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(3)], default=0)
    consequences_mild = models.CharField(max_length=256, blank=True)
    consequences_moderate = models.CharField(max_length=256, blank=True)
    consequences_severe = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return f"Personage: \n" \
               f"name: {self.pers_name!r}, pronoun: {self.pers_pronoun!r}, " \
               f"description: {self.pers_description!r}, parties: {self.get_parties()}"

    def get_parties(self):
        party = self.personageparty_set.all()
        return ', '.join(map(str, party))


class PersonageParty(models.Model):
    party = models.CharField(max_length=64)
    personage = models.ManyToManyField(Personage)

    def __str__(self):
        return self.party

charlist/myauth/forms.py
from django.contrib.auth.forms import UserCreationForm

from myauth.models import CharlistUser


class CharlistUserCreateForm(UserCreationForm):
    class Meta:
        model = CharlistUser
        fields = ('username', 'email', 'password1', 'password2')

charlist/personages/forms.py
from django.forms import ModelForm

from personages.models import Personage


class PersonageCreateForm(ModelForm):
    class Meta:
        model = Personage
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name)
            # print(field)
            field.widget.attrs['class'] = 'model-form'

charlist/myauth/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from myauth.forms import CharlistUserCreateForm
from myauth.models import CharlistUser


class NewUserRegister(CreateView):
    model = CharlistUser
    success_url = reverse_lazy('all_personages')
    # success_url = '/' # должен быть реверс лейзи по хорошему
    form_class = CharlistUserCreateForm

charlist/personages/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView
from personages.models import Personage

from personages.forms import PersonageCreateForm


@login_required
def all_personages(request):
    all_personages = Personage.objects.all()

    context = {
        'all_personages': all_personages,
    }

    return render(request, 'personages/all_personages.html', context=context)

# вариант FBV - Function Detailed View
# def personage_details(request, pk):
#     get_personage_details = get_object_or_404(Personage, pk=pk)
#
#     context = {
#         'page_title': 'Detail title',
#         'personage': get_personage_details, # контекст следует называть четко по имени класса
#     }
#
#     return render(request, 'personages/personage_detail.html', context=context)


class PageTitleMixin:
    page_title = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        return context


# вариант CBV - Class Detail View
class PersonageDetailView(PageTitleMixin, DetailView):
    # template_name = 'personages/personage_detail.html'  # автоматически вычисляется из имя класса + _detail
    model = Personage
    page_title = 'Personage detail'
    # pk_url_kwarg = 'pk' # нужно, если как primary key используется не 'pk' или 'slug'
    # context_object_name = 'personage_details' # можно переопределять, если нужен кастом,
                                                # но если не определено, за контекст берется имя класса


# @login_required # ERROR
# @permission_required('personages.add_personage')
# @user_passes_test(lambda u: u.is_superuser)
# class PersonageCreateView(LoginRequiredMixin, CreateView):
# class PersonageCreateView(PermissionRequiredMixin, CreateView):
class PersonageCreateView(UserPassesTestMixin, CreateView):
    # permission_required = 'personages.add_personage'  # для PermissionRequiredMixin
    model = Personage
    success_url = reverse_lazy('all_personages') #  обязательный параметр
    form_class = PersonageCreateForm
    # fields = '__all__'  #  обязательный параметр либо он, либо form_class

    def test_func(self):
        print(self.request.user)
        return self.request.user.is_superuser
        # if self.request.user.is_anonimous:  # ERROR не срабатывает
        #     print('Login to create')

    # все проверки на права делать на уровне вьюх


class PersonageUpdateView(UpdateView):
    model = Personage
    success_url = reverse_lazy('all_personages')
    fields = '__all__'

charlist/myauth/templates/myauth/charlistuser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
</head>
<body>
<div class="user-creation-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</div>
</body>
</html>

charlist/personages/templates/personages/all_personages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personages</title>
</head>
<body>
<a href="{% url 'personages:create'%}">Create new personage</a>
<br><a href="{% url 'myauth:register' %}"> register </a></br>
<br><a href="{% url 'myauth:login' %}"> login </a></br>

<h1>View all personages</h1>
<ul>{% for el in all_personages %}
    <li><a href="{% url 'personages:details' pk=el.pk %}"> {{ el }}  </a></li>
{% endfor %}
</ul>
</body>
</html>

charlist/personages/templates/personages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Charlist" }}</title>
</head>
<body>

{% block menu %}
    <ul>
      <li><a href="{% url 'all_personages' %}"> see all pers </a></li>
      <li>
        {% if user.is_anonimous %}
        <a href="{% url 'myauth:login' %}"> login </a>
        <a href="{% url 'myauth:register' %}"> register </a>
          {% else %}
          <a href="{% url 'myauth:logout' %}"> logout </a>
          {% endif %}
      </li>

    </ul>
{% endblock %}

{% block main_content %}
{% endblock %}

</body>
</html>

charlist/personages/templates/personages/personage_detail.html
{% extends 'personages/base.html' %}


{% block main_content %}
<h1>Hello {{user}}! </h1>
<p>{{ personage }}</p>

<a href="{% url 'personages:update' pk=personage.pk %}">Update this personage</a>
{% endblock %}

<!--ВСЕ, то пишется вне заданных в base блоков будет ОТБРОШЕНО-->

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>{{ page_title }}</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Hello {{user}}! </h1>-->
<!--    <ul>-->
<!--<li><a href="{% url 'pers_stats_main' %}"> main </a></li>-->
<!--<li><a href="{% url 'all_personages' %}"> see all pers </a></li>-->
<!--    </ul>-->
<!--   <p>{{ personage }}</p>-->
<!--</body>-->
<!--</html>-->

charlist/personages/templates/personages/personage_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personage action</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
<!--    {{ form.as_table }} дорабатывать таблицу дополнительно-->
<!--    {{ form.as_ul }} дорабатывать список дополнительно -->

    <input type="submit" value="save">
</form>
</body>
</html>